### ISSUE TITLE
Add delay to enable scrolling on mobile

### ISSUE THREAD

**Issue by sebastian-steinmann** [timruffles/ios-html5-drag-drop-shim#75] opened 2016-10-14 08:45 UTC
When working on a touch device the shim cant distinguish between scrolling and dragging.
Would be great to have a config to set a delay (typically 300ms) to hold before dragging is enabled.

This is closer to how it works on a native device.

**Comment by reppners** [comment] 2016-10-14 09:11
Choosing between scrolling and drag-drop on the same element based on gesture is tricky to implement and not obvious for the user which is why I recommend to avoid it.

Rather implement an explicit visual drag-handle which allows to drag while the rest of the element does allow scrolling without starting a drag-operation unintentionally.
Here is a rough example implementation on how to do this:
https://github.com/timruffles/ios-html5-drag-drop-shim/blob/d11a2adab36c76276f134d760e4fa6b7f6956f24/spec-compliance/index.html#L500-L605

There was a hook in beta.0 of the rewrite which allowed to do this was removed as it was error-prone and I didn't want to make it easy to shoot yourself in the foot. You can read about the issue in this comment:
https://github.com/timruffles/ios-html5-drag-drop-shim/pull/61#issuecomment-189924276

Having said that it might by possible to bring this deferred drag-start back by having an implementation that makes sure no browser scroll was initiated while keeping the finger pressed to initiate the drag operation after a small delay. Or there is some way to stop the browser from scrolling prior to starting the drag. If anyone knows of a way pls let me know.

**Comment by aevare** [comment] 2016-10-14 09:44
Not sure how to attach pull-request to issue, but I have done this with a setTimeout before calling start touch.
[Pull request](https://github.com/timruffles/ios-html5-drag-drop-shim/pull/76)

**Comment by sebastian-steinmann** [comment] 2016-10-14 10:00
#76

**Comment by sebastian-steinmann** [comment] 2016-10-14 10:12
Seems to fix it without the side-effects mentioned in the comments?

**Comment by reppners** [comment] 2016-10-14 10:18
Thx for the effort. Might be because the mechanism in the 1.0 is different than the 2.0-rewrite. Will check as soon as I can.

**Comment by reppners** [comment] 2016-10-14 22:10
On which device / os / browser did you verify that the delayed dragstart works without simultaneous scroll? Just tried out on iPhone6/iOS10/Safari and whilst the drag start is delayed I get simultaneous scrolling. What page do you use to test? Is it a nested scrollable container?

**Comment by sebastian-steinmann** [comment] 2016-10-17 06:49
Tested it on Chrome, and an Android device, but had a tingling it might be a problem with ios.
I'll see if I can get my hands on a mac to test.

**Comment by aevare** [comment] 2016-10-17 07:55
I'm testing on IOS 9.3.1 on iPhone 5s right now.
As long as I hold and wait to get the clone the view does not scroll. 
I will try to test on a newer device while at work.

**Comment by reppners** [comment] 2016-10-17 08:20
#77 might be a problem that affects what I experience.. guess I have to install the simulator to test with other iOS/Safari versions than what I have on my device.


> I'm testing on IOS 9.3.1 on iPhone 5s right now.
> As long as I hold and wait to get the clone the view does not scroll.

Does that mean when you start to scroll before the drag operation starts the scroll does not stop while dragging? ( effect described in https://github.com/timruffles/ios-html5-drag-drop-shim/pull/61#issuecomment-189924276 ) 
If so than maybe a solution can be found where the drag does not start when some scroll event bubbled up to the document.

**Comment by aevare** [comment] 2016-10-17 09:07
I have fixed it with a simple scroll listener, so if you start to scroll before the delay is reached the drag is cancelled and you scroll normally.
This way you don't have to worry about scroll when drag/drop items take the whole page.
If you hold long enough the scroll is cancelled.

I have to check out #77 as I don't have a iOS 10 device right now, only iOS 9.
But on Android, and iOS 9, you can not stop a scroll that has already started. If you prevent it on the first event, it does work (you stop the device from scrolling).

**Comment by reppners** [comment] 2016-10-17 09:11
will check your changes as soon as I have the simulators running 👍

**Comment by aevare** [comment] 2016-10-17 09:47
Great, I'm installing iOS 10 right now so I can test it too.

**Comment by aevare** [comment] 2016-10-17 10:10
The bug is still present in iOS 10, but I feel like that is unrelated to this issue/fix.

**Comment by reppners** [comment] 2016-10-18 21:51
Ran it in the iOS simulator with iOS 9 and iOS 10. iOS 9 is running fine. iOS 10 has the bug tracked by #77. Its a breaking change/regression in Safari. If the `touchstart` is prevented in the listener directly the browser does not scroll but this is not suitable for the drag and drop use case. Hopefully the webkit maintainers will fix this soon.

**Comment by sebastian-steinmann** [comment] 2016-10-19 11:50
So its better than before then? No new bugs, but new feature? I say merge & deploy ;)

**Comment by reppners** [comment] 2016-11-21 09:00
merged and released as of v1.2.0, thx for your contribution!

**Closed by reppners** 2016-11-21 09:00 UTC
